version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: yolo-server:v1.1.0
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - yolo-network

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - yolo-network

  client:
    build:
      context: ./client
    image: yolo-client:v1.1.0
    #Bind the container's port 80 to host port 3000
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge

volumes:
  mongodb_data:
