---
# Execute Terraform playbook on the localhost
- name: Execute Terraform
  hosts: localhost
  gather_facts: false  # No need to gather facts on localhost

  vars:
    terraform_dir: "./stage_two/terraform"  # Define the directory containing Terraform files

  tasks:
    # Task to initialize Terraform
    - name: Initialize Terraform
      ansible.builtin.command:
        cmd: "terraform init"
        chdir: "{{ terraform_dir }}"  # Change directory to the Terraform directory
      register: terraform_init  # Register the output of the command
      changed_when: terraform_init.stdout.find("Terraform has been successfully initialized") != -1  # Mark the task as changed if Terraform is successfully initialized

    # Task to apply Terraform configuration
    - name: Apply Terraform
      ansible.builtin.command:
        cmd: "terraform apply -auto-approve"
        chdir: "{{ terraform_dir }}"  # Change directory to the Terraform directory
      when: terraform_init is succeeded  # Execute this task only if Terraform initialization is successful

# Import the main playbook.yml after executing Terraform
- import_playbook: playbook.yml
