- name: Provisioning webservers
  hosts: all
  become: true
  vars:
    repo_url: https://github.com/felixmakinda/yolo.git
    user: ubuntu
    dest: /home/{{ user }}/yolo
    docker_images:
      - name: backend
        tag: 1.0.0
        path: "{{ dest }}/backend"
        port: "5000:5000"
      - name: client
        tag: 1.0.0
        path: "{{ dest }}/client"
        port: "3000:80"

  tasks:
    - name: Install Dependencies
      apt:
        name: 
          - python3-pip
          - git
        state: present

    - name: Install Docker Python SDK
      pip:
        name: docker==6.1.3
        state: present

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest }}"
        update: yes
        force: yes
        accept_hostkey: yes
        version: master

  roles:
    - role: build_client
      vars:
        dockerfile_path: "{{ dest }}/client"

    - role: build_backend
      vars:
        dockerfile_path: "{{ dest }}/backend"

  handlers:
    - name: restart docker
      docker_container:
        name: "{{ item.name }}"
        state: started
        restart_policy: always
      loop: "{{ docker_images }}"

    - name: Run Docker containers
      docker_container:
        name: "{{ item.name }}"
        image: "{{ item.name }}:{{ item.tag }}"
        state: started
        ports: "{{ item.port }}"
      loop: "{{ docker_images }}"
      notify: restart docker
